# https://github.com/pmarsceill/just-the-docs
remote_theme: pmarsceill/just-the-docs

logo: "/assets/images/just-the-docs.png"

# Aux links for the upper right navigation
aux_links:
  "FMGARAGE Homepage":
    - "//fmgarage.com"
